### ISSUE TITLE
Missing geofabric CC within RR relationships in small cache

### ISSUE THREAD

**Issue by shaneseaton** [CSIRO-enviro-informatics/loci-cache-scripts#1]
The following query produces no results in the SMALL CACHE, but does work in the LARGE CACHE. This could be simply because the the limited data in the small cache doesn't bring in enough RR's to cover any CC, but I am not sure about that...they should be within something
```
PREFIX geo: <http://www.opengis.net/ont/geosparql#>

SELECT *
where {
    ?child a <http://linked.data.gov.au/def/geofabric#ContractedCatchment> ;
         geo:sfWithin ?thing .
} 
```

**Comment by jyucsiro** [comment]
not relevant
