### ISSUE TITLE
Upload all linksets to auto-generated/linksets path on s3

### ISSUE THREAD

**Issue by benjaminleighton** [CSIRO-enviro-informatics/loci-cache-scripts#12]
This is likely a work around until we refactor cache load or naming conventions to differentiate between auto-generated linksets and other kinds or decide that there is no difference and just stick everything in a general linksets location. For now the following need to be reuploaded to the new path
```
ld_addrcatch.trig.sha256 
ls_addrcatch.trig
ls_addrcatch.ttl
ls_addrcatch.ttl.sha256
```

**Comment by shaneseaton** [comment]
This is just an issue now, while we are transitioning between the old manual process and the new automated way. Should be a non issue after the copy. It doesn't bring into question a larger issue of versioning, and how we go about it. Do the datasets should have a generation date, or version number in them somewhere so we know what set it is. The current process is to just blindly override the file that is there with the latest.

**Comment by benjaminleighton** [comment]
The issue I was trying to get at for the longer term is what do we mean by "auto-generated"? Are linksets created by others "auto-generated" and should they sit with a name (path) "auto-generated" because it is a bit confusing.

**Comment by shaneseaton** [comment]
Agree `auto-generated` is really just an indicator that it came out of the `loci-cache-scripts` process, but there is no reason that is the only place we should be looking to ingest into the cache from, nor is it probably the best name. At least the name is in a single place, so easy to change later.

**Comment by shaneseaton** [comment]
These files have been copied to the auto-gen area which will make the cache work again. They are also fine to be overwritten at any stage, and the cache will just pickup the new versions.
