### ISSUE TITLE
Modify cache docker to provide a deployment that defaults to not rebuilding

### ISSUE THREAD

**Issue by benjaminleighton** [CSIRO-enviro-informatics/loci-cache-scripts#18]
When a new cache is deployed it is built with `startup.sh --rebuild` that sets `FORCE_REFRESH=1` this instructs `build-cache.sh` to populate the graph database. On `docker restart` or subsequent to the restart policy being enacted on a machine reboot the cache will rebuild. 

Instead we need to refactor so that the container is running without `FORCE_REFRESH` set. This could happen as part of `startup.sh --rebuild`, first the container would be created with `FORCE_REFRESH` set, once the build process is complete the container (but not the volumes) can be removed with `docker-compose rm`. The variable can be unset with `unset FORCE_REFRESH`. Detecting that the cache build process run as part of `startup.sh --rebuild` has finished requires that there is some indication the build scripts have completed running. One approach would be to add a final script that runs to indicate load completion by writing a file to disk or setting an env variable within the container, the external script could then watch / wait for this indicator before stopping and regenerating the container.

**Comment by benjaminleighton** [comment]
@shaneseaton I think you've fixed this, can I close it?

**Comment by shaneseaton** [comment]
Fixed
